#line 2 "scanner.c"

#line 4 "scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 141
#define YY_END_OF_BUFFER 142
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[385] =
    {   0,
        0,    0,    2,    2,  142,  140,    6,    6,  105,  140,
      137,  140,   99,  140,  126,  127,   90,   84,   76,   87,
       82,   92,  132,   78,   77,  116,   74,  118,   79,  130,
      131,  103,  140,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  128,  101,  129,   98,    2,    4,    3,
        6,  114,    0,  134,  137,  137,   96,  108,  100,    0,
      135,   94,   91,   85,   86,   88,   89,    0,    1,    7,
       93,    0,  132,  139,  120,  117,  112,   75,  119,  122,
       80,  106,  104,    0,  136,  137,   54,  137,  137,  137,

      137,  137,  137,  137,   17,  137,  137,  137,  137,  137,
      137,  137,  137,  137,   26,  137,   29,  137,  137,  137,
      137,   58,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  102,   81,  110,    2,    3,    3,    5,  115,   97,
      109,   95,   83,    7,    7,  133,  121,  113,  123,  124,
      107,   61,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
       24,  137,  137,   57,  137,  137,  137,   32,  137,  137,
       33,  137,  137,  137,  137,  137,  137,  137,  137,   59,

      137,  137,  137,  137,  137,  137,  137,  137,  137,   45,
      137,  137,  137,   47,  137,  137,  137,  137,  111,    7,
      138,  125,  137,  137,  137,  137,    9,  137,  137,  137,
      137,  137,  137,  137,  137,   18,   19,  137,  137,  137,
      137,   56,  137,  137,  137,  137,  137,  137,  137,   34,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,   42,  137,   44,   71,  137,  137,   48,
      137,   50,  137,   55,   51,  137,    8,   10,   11,   12,
      137,  137,  137,  137,  137,  137,  137,   22,  137,  137,
      137,  137,  137,  137,  137,   67,  137,  137,  137,  137,

      137,  137,  137,  137,  137,   40,  137,  137,  137,   43,
      137,  137,  137,   49,   52,  137,  137,  137,  137,  137,
      137,   16,   20,  137,  137,  137,  137,   28,  137,  137,
       65,   68,  137,  137,  137,   38,  137,   39,   53,   69,
       41,   70,   60,   46,  137,  137,   62,  137,  137,  137,
       64,   15,   21,   23,  137,  137,  137,  137,   35,   36,
      137,   66,  137,   73,  137,   13,   14,   25,  137,  137,
      137,  137,  137,  137,  137,  137,   31,   37,   72,  137,
       27,   30,   63,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       26,    1,   27,   28,    6,   29,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   25,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   25,   54,   55,   56,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    5,    1,    6,    1,    1,
        1,    1,    1,    1,    6,    1,    1,    1,    1,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[396] =
    {   0,
        0,    0,   55,   56,  725,  726,   58,   60,  702,  718,
      704,  714,   56,  711,  726,  726,   53,   57,  726,   51,
      703,   59,   56,  726,  726,   61,   62,   64,   53,  726,
      726,  696,  688,   62,   71,   72,   73,   78,   93,   74,
       87,   76,   81,   85,  103,  107,  109,  114,  115,  108,
      117,  133,  126,  726,  118,  726,  726,    0,  726,   76,
       95,  694,  710,  726,  696,    0,  691,  690,  726,  702,
      726,  688,  726,  726,  726,  726,  726,  693,  726,  691,
      726,  689,  139,  156,  684,  726,  683,  726,  726,   78,
      726,  682,  726,  674,  726,  128,  131,  136,  140,  141,

      151,  158,  159,  160,  684,  161,  162,  168,  164,  167,
      169,  171,  175,  172,  683,  178,  176,  179,  185,  184,
      188,  682,  187,  195,  208,  192,  203,  212,  213,  207,
      214,  218,  223,  225,  226,  229,  230,  228,  234,  231,
      241,  726,  726,  677,    0,  248,  265,  726,  726,  726,
      726,  726,  726,    0,  681,  679,  726,  726,  726,  674,
      726,  677,  238,  235,  245,  253,  263,  266,  249,  268,
      269,  270,  271,  272,  273,  276,  277,  274,  275,  281,
      676,  282,  287,  675,  284,  285,  291,  674,  286,  294,
      673,  296,  295,  303,  311,  312,  313,  314,  316,  672,

      319,  320,  321,  322,  323,  326,  325,  328,  330,  671,
      332,  334,  327,  670,  341,  333,  338,  339,  726,  670,
      668,  726,  358,  329,  360,  362,  667,  363,  364,  365,
      366,  367,  368,  369,  371,  666,  665,  370,  373,  374,
      377,  664,  375,  378,  379,  384,  381,  388,  387,  663,
      392,  391,  402,  404,  406,  411,  389,  412,  413,  416,
      419,  418,  422,  662,  421,  661,  423,  424,  425,  660,
      429,  659,  427,  658,  657,  428,  656,  655,  654,  430,
      435,  434,  436,  439,  446,  447,  451,  653,  449,  453,
      455,  456,  457,  463,  460,  652,  465,  467,  468,  469,

      470,  472,  475,  474,  479,  651,  482,  487,  489,  650,
      490,  491,  492,  649,  648,  494,  495,  496,  504,  505,
      502,  647,  646,  506,  503,  508,  512,  645,  510,  517,
      644,  643,  514,  515,  513,  642,  523,  637,  634,  633,
      627,  623,  621,  604,  516,  522,  603,  534,  536,  537,
      588,  587,  586,  583,  542,  544,  541,  545,  582,  577,
      547,  576,  551,  575,  549,  574,  572,  569,  550,  553,
      554,  556,  558,  560,  555,  564,  562,  331,  236,  561,
      232,  189,   88,  726,  607,  613,  617,  623,  625,  631,
      637,  643,  647,  653,   89

    } ;

static const flex_int16_t yy_def[396] =
    {   0,
      384,    1,  385,  385,  384,  384,  384,  384,  384,  386,
      387,  384,  384,  388,  384,  384,  384,  384,  384,  384,
      384,  384,  389,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  390,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  384,  384,  384,  384,  391,  384,  392,
      384,  384,  386,  384,  387,  393,  384,  384,  384,  388,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  394,
      384,  384,  389,  389,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  390,  384,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  384,  384,  384,  391,  392,  392,  384,  384,  384,
      384,  384,  384,  394,  394,  395,  384,  384,  384,  384,
      384,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  384,  394,
      395,  384,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,    0,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384

    } ;

static const flex_int16_t yy_nxt[784] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   11,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   11,   41,   11,   42,
       43,   44,   45,   46,   11,   47,   48,   49,   50,   51,
       52,   11,   53,   54,   55,   56,   57,   59,   59,   61,
       61,   61,   61,   68,   72,   76,   60,   60,   91,   74,
       79,   82,   77,   83,   73,   80,   92,   69,   75,   66,
       81,   85,   86,   87,   88,   89,   90,  147,   66,   66,
       66,   66,  148,   66,  221,   66,   61,   61,   66,  159,

      160,  101,   66,   96,   66,   66,  104,  114,   97,  118,
       66,  102,   98,   99,  103,  105,  100,  106,  120,  107,
       66,  115,  109,  119,   66,   66,   66,  116,  117,  108,
      110,   66,   66,  121,   66,  111,  123,  122,  112,  142,
      143,  113,  126,   66,  132,   66,  137,  127,   66,  136,
       66,  133,  124,   66,   82,  125,   83,   66,   66,  138,
      134,  128,  129,  141,  130,  164,  131,  135,   66,  139,
      140,  384,  144,  384,  166,   66,   66,   66,   66,   66,
      162,   66,  165,  163,   66,   66,   66,  169,   66,   66,
      171,  172,   66,   66,  173,   66,   66,  167,  168,  174,

      170,   66,   66,  179,   66,   66,   66,  175,  180,   66,
      176,  177,   66,  182,  181,  178,  183,  189,  194,  184,
       66,  185,  186,  187,   66,   66,  188,  192,  193,   66,
       66,   66,  195,  190,  191,   66,  198,  196,  197,  199,
       66,  201,   66,   66,  204,   66,   66,   66,   66,   66,
      200,   66,   66,   66,  205,   66,  203,  202,   66,  384,
      207,  212,   66,  206,  384,  215,   66,  213,  208,  211,
       66,  216,  224,  209,  218,  214,  147,  210,  217,  223,
       66,  148,  226,   66,  225,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,  229,  227,  228,   66,   66,

      234,   66,   66,   66,   66,  235,  236,  239,   66,  233,
      241,   66,   66,   66,  230,  231,  237,  232,  243,  238,
       66,  240,  242,  244,  247,  251,  245,  249,   66,   66,
       66,   66,  246,   66,  248,  250,   66,   66,   66,   66,
       66,  252,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,  255,  262,  260,   66,   66,  259,   66,  254,
      253,  263,  256,  266,  257,  267,  258,  268,  269,  261,
      265,  264,  271,  270,  272,   66,  275,   66,  273,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,  274,
       66,   66,   66,  276,   66,   66,   66,  283,   66,  278,

      277,   66,  282,  281,   66,   66,   66,  288,   66,   66,
      279,  291,  280,  293,  287,  286,  289,  284,  285,   66,
      298,   66,  290,   66,  292,  297,  294,  295,   66,   66,
       66,  299,  296,   66,  303,   66,   66,  300,   66,   66,
       66,   66,   66,  301,   66,   66,   66,   66,  302,  304,
      307,   66,   66,   66,  305,  309,   66,  316,  312,  315,
      308,  306,  314,   66,   66,  311,   66,  313,   66,  319,
       66,  310,   66,   66,   66,  317,  318,   66,  321,  322,
       66,  320,   66,  324,   66,   66,   66,   66,  325,   66,
      326,   66,   66,  331,  323,  327,   66,  330,  329,   66,

      335,  336,  333,  328,   66,  339,   66,   66,   66,   66,
      332,   66,   66,   66,  340,  334,  338,  337,  341,   66,
       66,   66,   66,   66,  344,   66,  342,   66,  345,   66,
       66,   66,   66,   66,   66,  347,  343,  350,  351,   66,
       66,  357,  346,  348,  349,  356,  358,  359,  360,  352,
      355,   66,  353,   66,   66,  354,  362,  363,   66,   66,
      361,   66,   66,  364,   66,  365,   66,   66,   66,  366,
       66,   66,   66,   66,  370,   66,  371,   66,   66,   66,
      372,   66,  367,  368,  373,  369,   66,  377,  378,   66,
      379,   66,   66,   66,   66,  376,  374,  375,  382,   66,

       66,  381,  380,   66,   66,   66,  383,   58,   58,   58,
       58,   58,   58,   63,   63,   63,   63,   63,   63,   65,
       66,   66,   65,   70,   70,   70,   70,   70,   70,   84,
       84,   94,   94,   94,   94,   94,   94,  145,   66,  145,
       66,  145,  145,  146,   66,  146,  146,  146,  146,   66,
       66,   66,   66,  154,   66,  154,  154,  154,  154,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,  384,  155,   66,   66,   66,
       66,   66,   66,   66,   66,  222,  156,  220,  219,   66,

       66,   66,   95,  161,  158,  157,  156,  155,  153,  152,
       71,  151,  150,   66,   64,  149,   95,   93,   78,   71,
       67,   66,   64,   62,  384,    5,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384
    } ;

static const flex_int16_t yy_chk[784] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    7,
        7,    8,    8,   13,   17,   20,    3,    4,   29,   18,
       22,   23,   20,   23,   17,   22,   29,   13,   18,   34,
       22,   26,   26,   27,   27,   28,   28,   60,   35,   36,
       37,   40,   60,   42,  395,   38,   61,   61,   43,   90,

       90,   36,   44,   34,   41,  383,   37,   40,   34,   42,
       39,   36,   34,   35,   36,   37,   35,   38,   44,   38,
       45,   41,   39,   43,   46,   50,   47,   41,   41,   38,
       39,   48,   49,   44,   51,   39,   46,   45,   39,   55,
       55,   39,   47,   53,   49,   96,   51,   48,   97,   50,
       52,   49,   46,   98,   83,   46,   83,   99,  100,   51,
       49,   48,   48,   53,   48,   98,   48,   49,  101,   52,
       52,   84,   55,   84,  100,  102,  103,  104,  106,  107,
       96,  109,   99,   97,  110,  108,  111,  102,  112,  114,
      104,  104,  113,  117,  104,  116,  118,  101,  101,  104,

      103,  120,  119,  109,  123,  121,  382,  106,  110,  126,
      107,  108,  124,  112,  111,  108,  113,  119,  123,  114,
      127,  116,  117,  117,  130,  125,  118,  121,  121,  128,
      129,  131,  124,  120,  120,  132,  126,  124,  125,  126,
      133,  128,  134,  135,  130,  138,  136,  137,  140,  381,
      127,  139,  164,  379,  131,  163,  129,  128,  141,  146,
      133,  136,  165,  132,  146,  138,  169,  136,  133,  135,
      166,  139,  164,  134,  141,  137,  147,  134,  140,  163,
      167,  147,  166,  168,  165,  170,  171,  172,  173,  174,
      175,  178,  179,  176,  177,  169,  167,  168,  180,  182,

      173,  185,  186,  189,  183,  174,  175,  178,  187,  172,
      180,  190,  193,  192,  170,  170,  176,  171,  183,  177,
      194,  179,  182,  185,  187,  193,  185,  190,  195,  196,
      197,  198,  186,  199,  189,  192,  201,  202,  203,  204,
      205,  194,  207,  206,  213,  208,  224,  209,  378,  211,
      216,  212,  197,  205,  203,  217,  218,  202,  215,  196,
      195,  206,  198,  209,  199,  211,  201,  212,  213,  204,
      208,  207,  216,  215,  217,  223,  224,  225,  218,  226,
      228,  229,  230,  231,  232,  233,  234,  238,  235,  223,
      239,  240,  243,  225,  241,  244,  245,  233,  247,  228,

      226,  246,  232,  231,  249,  248,  257,  240,  252,  251,
      229,  244,  230,  246,  239,  238,  241,  234,  235,  253,
      252,  254,  243,  255,  245,  251,  247,  248,  256,  258,
      259,  253,  249,  260,  257,  262,  261,  254,  265,  263,
      267,  268,  269,  255,  273,  276,  271,  280,  256,  258,
      261,  282,  281,  283,  259,  263,  284,  276,  268,  273,
      262,  260,  271,  285,  286,  267,  289,  269,  287,  282,
      290,  265,  291,  292,  293,  280,  281,  295,  284,  285,
      294,  283,  297,  287,  298,  299,  300,  301,  289,  302,
      290,  304,  303,  295,  286,  291,  305,  294,  293,  307,

      300,  301,  298,  292,  308,  304,  309,  311,  312,  313,
      297,  316,  317,  318,  305,  299,  303,  302,  307,  321,
      325,  319,  320,  324,  311,  326,  308,  329,  312,  327,
      335,  333,  334,  345,  330,  316,  309,  319,  320,  346,
      337,  329,  313,  317,  318,  327,  330,  333,  334,  321,
      326,  348,  324,  349,  350,  325,  337,  345,  357,  355,
      335,  356,  358,  346,  361,  348,  365,  369,  363,  349,
      370,  371,  375,  372,  357,  373,  358,  374,  380,  377,
      361,  376,  350,  355,  363,  356,  368,  371,  372,  367,
      373,  366,  364,  362,  360,  370,  365,  369,  376,  359,

      354,  375,  374,  353,  352,  351,  380,  385,  385,  385,
      385,  385,  385,  386,  386,  386,  386,  386,  386,  387,
      347,  344,  387,  388,  388,  388,  388,  388,  388,  389,
      389,  390,  390,  390,  390,  390,  390,  391,  343,  391,
      342,  391,  391,  392,  341,  392,  392,  392,  392,  393,
      340,  339,  393,  394,  338,  394,  394,  394,  394,  336,
      332,  331,  328,  323,  322,  315,  314,  310,  306,  296,
      288,  279,  278,  277,  275,  274,  272,  270,  266,  264,
      250,  242,  237,  236,  227,  221,  220,  214,  210,  200,
      191,  188,  184,  181,  162,  160,  156,  155,  144,  122,

      115,  105,   94,   92,   87,   85,   82,   80,   78,   72,
       70,   68,   67,   65,   63,   62,   33,   32,   21,   14,
       12,   11,   10,    9,    5,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[142] =
    {   0,
0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 
    0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define YY_NO_INPUT 1
#line 8 "scanner.l"

#include <stdio.h>
#include "parser.h"

void processar_token(char*);
void erro_lexico(int);

#line 787 "scanner.c"

#line 789 "scanner.c"

#define INITIAL 0
#define comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 30 "scanner.l"


#line 33 "scanner.l"
	/* Ignorados */

#line 1011 "scanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 385 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 726 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "scanner.l"
{ BEGIN(comment); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 36 "scanner.l"
{ /* Fazer nada */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 37 "scanner.l"
{ /* Fazer nada */ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 38 "scanner.l"
{ /* Fazer nada */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "scanner.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 41 "scanner.l"
{ /* Fazer nada */ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "scanner.l"
{ /* Fazer nada */ }
	YY_BREAK
/* Nao podem ser identificadores */
case 8:
YY_RULE_SETUP
#line 47 "scanner.l"
{ processar_token("BREAK"); return BREAK; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "scanner.l"
{ processar_token("CASE"); return CASE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "scanner.l"
{ processar_token("CATCH"); return CATCH; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "scanner.l"
{ processar_token("CLASS"); return CLASS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 "scanner.l"
{ processar_token("CONST_RW"); return CONST_RW; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "scanner.l"
{ processar_token("CONTINUE"); return CONTINUE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "scanner.l"
{ processar_token("DEBUGGER"); return DEBUGGER; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "scanner.l"
{ processar_token("DEFAULT"); return DEFAULT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "scanner.l"
{ processar_token("DELETE"); return DELETE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "scanner.l"
{ processar_token("DO"); return DO; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "scanner.l"
{ processar_token("ELSE"); return ELSE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "scanner.l"
{ processar_token("ENUM"); return ENUM; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "scanner.l"
{ processar_token("EXPORT"); return EXPORT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "scanner.l"
{ processar_token("EXTENDS"); return EXTENDS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "scanner.l"
{ processar_token("FALSE_RW"); return FALSE_RW; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "scanner.l"
{ processar_token("FINALLY"); return FINALLY; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "scanner.l"
{ processar_token("FOR"); return FOR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "scanner.l"
{ processar_token("FUNCTION"); return FUNCTION; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "scanner.l"
{ processar_token("IF"); return IF; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 "scanner.l"
{ processar_token("IMPLEMENTS"); return IMPLEMENTS; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "scanner.l"
{ processar_token("IMPORT"); return IMPORT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 68 "scanner.l"
{ processar_token("IN"); return IN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 69 "scanner.l"
{ processar_token("INSTANCEOF"); return INSTANCEOF; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 "scanner.l"
{ processar_token("INTERFACE"); return INTERFACE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 "scanner.l"
{ processar_token("LET"); return LET; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 72 "scanner.l"
{ processar_token("NEW"); return NEW; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 73 "scanner.l"
{ processar_token("NULL_RW"); return NULL_RW; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 "scanner.l"
{ processar_token("PACKAGE"); return PACKAGE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 "scanner.l"
{ processar_token("PRIVATE"); return PRIVATE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "scanner.l"
{ processar_token("PROTECTED"); return PROTECTED; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "scanner.l"
{ processar_token("PUBLIC"); return PUBLIC; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 "scanner.l"
{ processar_token("RETURN"); return RETURN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "scanner.l"
{ processar_token("SUPER"); return SUPER; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "scanner.l"
{ processar_token("SWITCH"); return SWITCH; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "scanner.l"
{ processar_token("THIS"); return THIS; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "scanner.l"
{ processar_token("THROW"); return THROW; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "scanner.l"
{ processar_token("TRUE_RW"); return TRUE_RW; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 84 "scanner.l"
{ processar_token("TRY"); return TRY; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "scanner.l"
{ processar_token("TYPEOF"); return TYPEOF; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 86 "scanner.l"
{ processar_token("VAR"); return VAR; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 87 "scanner.l"
{ processar_token("VOID_RW"); return VOID_RW; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 88 "scanner.l"
{ processar_token("WHILE"); return WHILE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 89 "scanner.l"
{ processar_token("WITH"); return WITH; }
	YY_BREAK
/* Podem ser identificadores */
case 51:
YY_RULE_SETUP
#line 94 "scanner.l"
{ processar_token("AWAIT"); return AWAIT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 95 "scanner.l"
{ processar_token("YIELD"); return YIELD; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 97 "scanner.l"
{ processar_token("STATIC"); return STATIC; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 99 "scanner.l"
{ processar_token("AS"); return AS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 100 "scanner.l"
{ processar_token("ASYNC"); return ASYNC; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 101 "scanner.l"
{ processar_token("FROM"); return FROM; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 102 "scanner.l"
{ processar_token("GET"); return GET; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 103 "scanner.l"
{ processar_token("OF"); return OF; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 104 "scanner.l"
{ processar_token("SET"); return SET; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 105 "scanner.l"
{ processar_token("TARGET"); return TARGET; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 107 "scanner.l"
{ processar_token("ANY"); return ANY; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 108 "scanner.l"
{ processar_token("BOOLTYPE"); return BOOLTYPE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 109 "scanner.l"
{ processar_token("CONSTRUCTOR"); return CONSTRUCTOR; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 110 "scanner.l"
{ processar_token("DECLARE"); return DECLARE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 111 "scanner.l"
{ processar_token("MODULE"); return MODULE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 112 "scanner.l"
{ processar_token("REQUIRE"); return REQUIRE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 113 "scanner.l"
{ processar_token("NEVER"); return NEVER; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 114 "scanner.l"
{ processar_token("NUMBER"); return NUMBER; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 115 "scanner.l"
{ processar_token("STRING"); return STRING; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 116 "scanner.l"
{ processar_token("SYMBOL"); return SYMBOL; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 117 "scanner.l"
{ processar_token("TYPE"); return TYPE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 118 "scanner.l"
{ processar_token("UNDEFINED"); return UNDEFINED; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 119 "scanner.l"
{ processar_token("UNKNOWN"); return UNKNOWN; }
	YY_BREAK
/* Pontuadores */
case 74:
YY_RULE_SETUP
#line 124 "scanner.l"
{ processar_token("ASSIGN"); return ASSIGN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 125 "scanner.l"
{ processar_token("ARROW"); return ARROW; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 126 "scanner.l"
{ processar_token("COMMA"); return COMMA; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 127 "scanner.l"
{ processar_token("SEMI"); return SEMI; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 128 "scanner.l"
{ processar_token("COLON"); return COLON; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 129 "scanner.l"
{ processar_token("TERNARY"); return TERNARY; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 130 "scanner.l"
{ processar_token("CHAIN"); return CHAIN; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 131 "scanner.l"
{ processar_token("PIPELINE"); return PIPELINE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 132 "scanner.l"
{ processar_token("DOT"); return DOT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 133 "scanner.l"
{ processar_token("SPREAD"); return SPREAD; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 135 "scanner.l"
{ processar_token("PLUS"); return PLUS; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 136 "scanner.l"
{ processar_token("INCREMENT"); return INCREMENT; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 137 "scanner.l"
{ processar_token("PLUS_ASSIGN"); return PLUS_ASSIGN; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 138 "scanner.l"
{ processar_token("SUB"); return SUB; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 139 "scanner.l"
{ processar_token("DECREMENT"); return DECREMENT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 140 "scanner.l"
{ processar_token("SUB_ASSIGN"); return SUB_ASSIGN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 141 "scanner.l"
{ processar_token("MULT"); return MULT; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 142 "scanner.l"
{ processar_token("MULT_ASSIGN"); return MULT_ASSIGN; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 143 "scanner.l"
{ processar_token("DIV"); return DIV; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 144 "scanner.l"
{ processar_token("DIV_ASSIGN"); return DIV_ASSIGN; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 145 "scanner.l"
{ processar_token("EXP"); return EXP; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 146 "scanner.l"
{ processar_token("EXP_ASSIGN"); return EXP_ASSIGN; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 147 "scanner.l"
{ processar_token("REM"); return REM; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 148 "scanner.l"
{ processar_token("REM_ASSIGN"); return REM_ASSIGN; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 150 "scanner.l"
{ processar_token("BITWISE_NOT"); return BITWISE_NOT; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 151 "scanner.l"
{ processar_token("BITWISE_AND"); return BITWISE_AND; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 152 "scanner.l"
{ processar_token("BITWISE_AND_ASSIGN"); return BITWISE_AND_ASSIGN; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 153 "scanner.l"
{ processar_token("BITWISE_OR"); return BITWISE_OR; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 154 "scanner.l"
{ processar_token("BITWISE_OR_ASSIGN"); return BITWISE_OR_ASSIGN; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 155 "scanner.l"
{ processar_token("BITWISE_XOR"); return BITWISE_XOR; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 156 "scanner.l"
{ processar_token("BITWISE_XOR_ASSIGN"); return BITWISE_XOR_ASSIGN; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 158 "scanner.l"
{ processar_token("LOGICAL_NOT"); return LOGICAL_NOT; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 159 "scanner.l"
{ processar_token("LOGICAL_NULL"); return LOGICAL_NULL; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 160 "scanner.l"
{ processar_token("LOGICAL_NULL_ASSIGN"); return LOGICAL_NULL_ASSIGN; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 161 "scanner.l"
{ processar_token("LOGICAL_AND"); return LOGICAL_AND; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 162 "scanner.l"
{ processar_token("LOGICAL_AND_ASSIGN"); return LOGICAL_AND_ASSIGN; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 163 "scanner.l"
{ processar_token("LOGICAL_OR"); return LOGICAL_OR; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 164 "scanner.l"
{ processar_token("LOGICAL_OR_ASSIGN"); return LOGICAL_OR_ASSIGN; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 166 "scanner.l"
{ processar_token("EQ"); return EQ; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 167 "scanner.l"
{ processar_token("EQ_STRICT"); return EQ_STRICT; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 168 "scanner.l"
{ processar_token("INEQ"); return INEQ; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 169 "scanner.l"
{ processar_token("INEQ_STRICT"); return INEQ_STRICT; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 170 "scanner.l"
{ processar_token("LT"); return LT; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 171 "scanner.l"
{ processar_token("LT_EQ"); return LT_EQ; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 172 "scanner.l"
{ processar_token("GT"); return GT; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 173 "scanner.l"
{ processar_token("GT_EQ"); return GT_EQ; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 175 "scanner.l"
{ processar_token("LSHIFT"); return LSHIFT; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 176 "scanner.l"
{ processar_token("LSHIFT_ASSIGN"); return LSHIFT_ASSIGN; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 177 "scanner.l"
{ processar_token("RSHIFT"); return RSHIFT; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 178 "scanner.l"
{ processar_token("RSHIFT_ASSIGN"); return RSHIFT_ASSIGN; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 179 "scanner.l"
{ processar_token("RSHIFT_UNSIGNED"); return RSHIFT_UNSIGNED; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 180 "scanner.l"
{ processar_token("RSHIFT_UNSIGNED_ASSIGN"); return RSHIFT_UNSIGNED_ASSIGN; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 182 "scanner.l"
{ processar_token("LPAR"); return LPAR; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 183 "scanner.l"
{ processar_token("RPAR"); return RPAR; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 184 "scanner.l"
{ processar_token("LBRACE"); return LBRACE; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 185 "scanner.l"
{ processar_token("RBRACE"); return RBRACE; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 186 "scanner.l"
{ processar_token("LBRACKET"); return LBRACKET; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 187 "scanner.l"
{ processar_token("RBRACKET"); return RBRACKET; }
	YY_BREAK
/* Valores */
case 132:
YY_RULE_SETUP
#line 192 "scanner.l"
{ processar_token("INT_VAL"); return INT_VAL; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 193 "scanner.l"
{ processar_token("REAL_VAL"); return REAL_VAL; }
	YY_BREAK
case 134:
/* rule 134 can match eol */
YY_RULE_SETUP
#line 194 "scanner.l"
{ processar_token("STR_VAL"); return STR_VAL; }
	YY_BREAK
case 135:
/* rule 135 can match eol */
YY_RULE_SETUP
#line 195 "scanner.l"
{ processar_token("STR_VAL"); return STR_VAL; }
	YY_BREAK
case 136:
/* rule 136 can match eol */
YY_RULE_SETUP
#line 196 "scanner.l"
{ processar_token("STR_VAL"); return STR_VAL; }
	YY_BREAK
/* Identificadores */
case 137:
YY_RULE_SETUP
#line 201 "scanner.l"
{ processar_token("ID"); return ID; }
	YY_BREAK
/* Erros */
case 138:
YY_RULE_SETUP
#line 206 "scanner.l"
{ erro_lexico(3); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 207 "scanner.l"
{ erro_lexico(2); }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 208 "scanner.l"
{ erro_lexico(1); }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 210 "scanner.l"
ECHO;
	YY_BREAK
#line 1794 "scanner.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 385 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 385 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 384);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 210 "scanner.l"


void processar_token(char* type)
{
	printf("%d: %s -> %s\n", yylineno, yytext, type);
}

void erro_lexico(int err_num)
{
	switch(err_num) {

		case 1:
			// Leitura de simbolo desconhecido
			fprintf(yyout, "LEXICAL ERROR (%d): Unknown symbol %s\n", yylineno, yytext);
			exit(EXIT_FAILURE);
			break;

		case 2:
			// Formato de identificador invalido
			fprintf(yyout, "LEXICAL ERROR (%d): Invalid ID %s\n", yylineno, yytext);
			exit(EXIT_FAILURE);
			break;

		case 3:
			// Formato de valor invalido
			fprintf(yyout, "LEXICAL ERROR (%d): Invalid value %s\n", yylineno, yytext);
			exit(EXIT_FAILURE);
			break;
	}
}
