#line 2 "scanner.c"

#line 4 "scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 139
#define YY_END_OF_BUFFER 140
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[382] =
    {   0,
        0,    0,    2,    2,  140,  138,    6,    6,  105,  138,
      137,   96,   99,  138,  126,  127,   90,   84,   76,   87,
       82,   92,  132,   78,   77,  116,   74,  118,   79,  130,
      131,  103,  138,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  128,  101,  129,   98,    2,    4,    3,
        6,  114,    0,  134,  137,  137,   97,  108,  100,    0,
      135,   94,   91,   85,   86,   88,   89,    0,    1,    7,
       93,    0,  132,  120,  117,  112,   75,  119,  122,   80,
      106,  104,    0,  136,  137,   54,  137,  137,  137,  137,

      137,  137,  137,   17,  137,  137,  137,  137,  137,  137,
      137,  137,  137,   26,  137,   29,  137,  137,  137,  137,
       58,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      102,   81,  110,    2,    3,    3,    5,  115,  109,   95,
       83,    7,    7,  133,  121,  113,  123,  124,  107,   61,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,   24,  137,
      137,   57,  137,  137,  137,   32,  137,  137,   33,  137,
      137,  137,  137,  137,  137,  137,  137,   59,  137,  137,

      137,  137,  137,  137,  137,  137,  137,   45,  137,  137,
      137,   47,  137,  137,  137,  137,  111,    7,  125,  137,
      137,  137,  137,    9,  137,  137,  137,  137,  137,  137,
      137,  137,   18,   19,  137,  137,  137,  137,   56,  137,
      137,  137,  137,  137,  137,  137,   34,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
       42,  137,   44,   71,  137,  137,   48,  137,   50,  137,
       55,   51,  137,    8,   10,   11,   12,  137,  137,  137,
      137,  137,  137,  137,   22,  137,  137,  137,  137,  137,
      137,  137,   67,  137,  137,  137,  137,  137,  137,  137,

      137,  137,   40,  137,  137,  137,   43,  137,  137,  137,
       49,   52,  137,  137,  137,  137,  137,  137,   16,   20,
      137,  137,  137,  137,   28,  137,  137,   65,   68,  137,
      137,  137,   38,  137,   39,   53,   69,   41,   70,   60,
       46,  137,  137,   62,  137,  137,  137,   64,   15,   21,
       23,  137,  137,  137,  137,   35,   36,  137,   66,  137,
       73,  137,   13,   14,   25,  137,  137,  137,  137,  137,
      137,  137,  137,   31,   37,   72,  137,   27,   30,   63,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
       25,    1,   26,   27,    6,   28,   29,   30,   31,   32,

       33,   34,   35,   36,   37,    6,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,    6,   53,   54,   55,   56,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[57] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[391] =
    {   0,
        0,    0,   54,   55,  701,  702,   57,   59,  678,  694,
      680,  675,   55,  687,  702,  702,   52,   56,  702,   50,
      679,   58,   55,  702,  702,   60,   61,   63,   52,  702,
      702,  672,  665,   61,   70,   71,   72,   77,   88,   75,
       86,   76,   79,  101,   69,  106,  104,  105,  111,  121,
      130,  124,  113,  702,  121,  702,  702,    0,  702,   79,
       96,  670,  686,  702,  672,    0,  702,  667,  702,  679,
      702,  665,  702,  702,  702,  702,  702,  670,  702,  668,
      702,  666,  148,  661,  702,  660,  702,  702,  123,  702,
      659,  702,  652,  702,  140,  147,  149,  151,  150,  155,

      152,  153,  156,  661,  158,  159,  162,  161,  167,  166,
      164,  171,  170,  660,  173,  178,  179,  195,  180,  192,
      659,  197,  196,  204,  200,  201,  217,  202,  203,  218,
      205,  219,  221,  223,  225,  231,  224,  233,  234,  235,
      702,  702,  654,    0,  242,  243,  702,  702,  702,  702,
      702,    0,  658,  656,  702,  702,  702,  651,  702,  654,
      247,  249,  253,  254,  256,  259,  257,  260,  261,  262,
      264,  266,  267,  273,  269,  277,  276,  279,  653,  278,
      284,  652,  286,  280,  287,  651,  294,  296,  650,  298,
      301,  303,   83,  299,  305,  306,  308,  649,  312,  314,

      315,  316,  317,  318,  320,  322,  325,  648,  327,  332,
      321,  647,  337,  331,  339,  334,  702,  647,  702,  343,
      349,  350,  353,  645,  354,  358,  359,  360,  363,  364,
      361,  366,  644,  643,  362,  367,  368,  371,  642,  369,
      370,  374,  376,  377,  381,  382,  641,  384,  394,  396,
      393,  397,  400,  403,  406,  410,  411,  413,  412,  414,
      640,  415,  639,  417,  418,  420,  638,  422,  637,  421,
      636,  635,  428,  634,  633,  632,  423,  431,  432,  424,
      427,  440,  442,  443,  631,  445,  446,  452,  453,  456,
      459,  458,  630,  460,  461,  462,  463,  464,  467,  469,

      468,  472,  629,  470,  480,  483,  628,  484,  485,  486,
      627,  626,  490,  493,  495,  496,  499,  497,  625,  624,
      502,  498,  503,  505,  623,  506,  510,  622,  621,  507,
      509,  508,  620,  516,  619,  618,  617,  616,  615,  614,
      613,  515,  517,  612,  528,  529,  533,  611,  608,  604,
      601,  534,  535,  536,  539,  581,  580,  546,  579,  547,
      578,  542,  577,  576,  574,  543,  545,  548,  550,  553,
      549,  554,  559,  570,  568,  566,  556,  565,  555,  185,
      702,  601,  605,  138,  609,  613,  617,  620,   89,  624
    } ;

static const flex_int16_t yy_def[391] =
    {   0,
      381,    1,  382,  382,  381,  381,  381,  381,  381,  383,
      384,  381,  381,  385,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  386,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  381,  381,  381,  381,  387,  381,  388,
      381,  381,  383,  381,  384,  389,  381,  381,  381,  385,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  390,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  386,  381,  384,  384,  384,  384,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      381,  381,  381,  387,  388,  388,  381,  381,  381,  381,
      381,  390,  390,  381,  381,  381,  381,  381,  381,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  381,  390,  381,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
        0,  381,  381,  381,  381,  381,  381,  381,  381,  381
    } ;

static const flex_int16_t yy_nxt[759] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   11,   41,   11,   42,   43,
       44,   45,   46,   11,   47,   48,   49,   50,   51,   52,
       11,   53,   54,   55,   56,   57,   59,   59,   61,   61,
       61,   61,   68,   72,   76,   60,   60,   90,   74,   79,
       82,   77,   83,   73,   80,   91,   69,   75,   66,   81,
       84,   85,   86,   87,   88,   89,   66,   66,   66,   66,
      146,   66,   66,   66,   66,  147,   66,   61,   61,  100,

       66,   95,  121,   66,  103,   66,   96,  113,  117,  101,
       97,   98,  102,  104,   99,  105,  108,  106,   66,  114,
      118,   66,   66,   66,  109,  115,  116,  107,   66,  110,
       66,  250,  111,  119,  122,  112,  125,  126,   66,  131,
       65,   66,  141,  142,  157,  158,  132,   66,  120,  140,
      123,  127,  128,  124,  129,  133,  130,   66,  136,  138,
      139,  135,  134,   82,   66,   83,   66,   66,   66,   66,
       66,  137,   66,   66,  143,   66,   66,  162,   66,   66,
      167,   66,  164,   66,   66,  169,  170,   66,   66,  171,
       66,  160,  163,  168,  172,   66,   66,   66,  161,  177,

      165,  166,   66,  173,  175,  180,  174,  178,  176,   66,
      179,  181,   66,   66,   66,  183,  182,   66,   66,   66,
       66,   66,   66,  184,  185,  186,  187,  192,  188,  189,
      190,  191,  193,  195,   66,   66,   66,  194,   66,  202,
       66,   66,   66,  196,  201,  199,  197,  198,   66,  204,
       66,   66,   66,  381,  146,  205,  210,  203,  381,  147,
      213,  200,  211,  206,   66,  209,   66,  216,  207,  214,
       66,   66,  208,   66,   66,  212,   66,   66,   66,   66,
      215,   66,  223,   66,   66,  221,   66,  220,  224,  225,
       66,  222,  231,   66,   66,   66,   66,   66,  232,  233,

      230,   66,  226,   66,   66,  227,  228,  238,  229,  236,
      235,   66,  234,   66,  240,   66,   66,  239,   66,  244,
       66,  237,   66,   66,  241,   66,  243,  242,  246,   66,
      248,   66,   66,   66,   66,   66,  247,   66,   66,   66,
      249,  245,   66,  252,   66,  251,  259,  257,   66,   66,
      256,   66,  260,  253,   66,  254,   66,  263,  255,  264,
       66,  266,  258,  262,  265,  261,   66,   66,  267,  268,
       66,   66,  270,  271,  269,   66,   66,   66,   66,   66,
       66,   66,  273,   66,   66,   66,   66,   66,   66,  275,
      274,   66,  280,   66,   66,  272,  278,  279,   66,   66,

      285,   66,  288,  276,  290,  277,  283,  284,  281,  286,
       66,   66,  282,   66,   66,  287,  294,   66,  289,  292,
       66,  291,  295,   66,  296,  297,  293,   66,   66,   66,
       66,   66,   66,  298,   66,   66,  299,   66,   66,   66,
       66,   66,  301,  304,   66,   66,  306,  300,   66,   66,
      302,  309,  312,  305,  311,  303,  313,   66,  308,   66,
       66,  310,   66,   66,  307,  318,  316,  314,  317,   66,
       66,  315,  319,   66,  321,   66,   66,   66,   66,   66,
       66,   66,  323,  322,   66,   66,   66,   66,  320,   66,
      328,  324,  327,  332,  333,  330,  326,   66,  336,  325,

       66,   66,   66,   66,  329,  338,  337,   66,  331,  335,
       66,  334,   66,   66,   66,   66,   66,  341,  339,   66,
       66,  342,   66,   66,   66,   66,   66,   66,  347,  340,
      344,  348,   66,   66,   66,  343,  354,  353,  355,  356,
      345,  357,  346,  349,  352,   66,   66,  350,  359,  351,
       66,   66,   66,   66,  358,  360,   66,  361,  362,   66,
       66,  363,   66,   66,   66,   66,   66,   66,  367,  368,
       66,   66,   66,   66,  365,  366,   66,  364,  369,  370,
      374,  375,   66,   66,  376,   66,  373,   66,  371,  372,
      377,   66,  379,   66,   66,   66,   66,   66,   66,  378,

      380,   58,   58,   58,   58,   63,   63,   63,   63,   70,
       70,   70,   70,   93,   93,   93,   93,  144,   66,  144,
      145,   66,  145,  145,  152,   66,  152,  152,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,  153,   66,   66,   66,   66,   66,   66,
       66,   66,  219,  154,  218,  217,   66,   66,   66,   94,
      159,  156,  155,  154,  153,  151,  150,   71,  149,   66,
       64,  148,   94,   92,   78,   71,   67,   66,   64,   62,

      381,    5,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381
    } ;

static const flex_int16_t yy_chk[759] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    7,    7,
        8,    8,   13,   17,   20,    3,    4,   29,   18,   22,
       23,   20,   23,   17,   22,   29,   13,   18,   34,   22,
       26,   26,   27,   27,   28,   28,   45,   35,   36,   37,
       60,  389,   40,   42,   38,   60,   43,   61,   61,   36,

      193,   34,   45,   41,   37,   39,   34,   40,   42,   36,
       34,   35,   36,   37,   35,   38,   39,   38,   44,   41,
       43,   47,   48,   46,   39,   41,   41,   38,   49,   39,
       53,  193,   39,   44,   46,   39,   47,   48,   50,   49,
      384,   52,   55,   55,   89,   89,   49,   51,   44,   53,
       46,   48,   48,   46,   48,   49,   48,   95,   51,   52,
       52,   50,   49,   83,   96,   83,   97,   99,   98,  101,
      102,   51,  100,  103,   55,  105,  106,   97,  108,  107,
      101,  111,   99,  110,  109,  103,  103,  113,  112,  103,
      115,   95,   98,  102,  103,  116,  117,  119,   96,  108,

      100,  100,  380,  105,  107,  111,  106,  109,  107,  120,
      110,  112,  118,  123,  122,  115,  113,  125,  126,  128,
      129,  124,  131,  116,  116,  117,  118,  122,  119,  119,
      120,  120,  123,  124,  127,  130,  132,  123,  133,  129,
      134,  137,  135,  125,  128,  127,  125,  126,  136,  131,
      138,  139,  140,  145,  146,  132,  135,  130,  145,  146,
      137,  127,  135,  132,  161,  134,  162,  140,  133,  138,
      163,  164,  133,  165,  167,  136,  166,  168,  169,  170,
      139,  171,  164,  172,  173,  162,  175,  161,  165,  166,
      174,  163,  171,  177,  176,  180,  178,  184,  172,  173,

      170,  181,  167,  183,  185,  168,  168,  178,  169,  176,
      175,  187,  174,  188,  181,  190,  194,  180,  191,  185,
      192,  177,  195,  196,  183,  197,  184,  183,  188,  199,
      191,  200,  201,  202,  203,  204,  190,  205,  211,  206,
      192,  187,  207,  195,  209,  194,  203,  201,  214,  210,
      200,  216,  204,  196,  213,  197,  215,  207,  199,  209,
      220,  211,  202,  206,  210,  205,  221,  222,  213,  214,
      223,  225,  216,  220,  215,  226,  227,  228,  231,  235,
      229,  230,  222,  232,  236,  237,  240,  241,  238,  225,
      223,  242,  230,  243,  244,  221,  228,  229,  245,  246,

      237,  248,  241,  226,  243,  227,  235,  236,  231,  238,
      251,  249,  232,  250,  252,  240,  248,  253,  242,  245,
      254,  244,  249,  255,  250,  251,  246,  256,  257,  259,
      258,  260,  262,  252,  264,  265,  253,  266,  270,  268,
      277,  280,  255,  258,  281,  273,  260,  254,  278,  279,
      256,  265,  270,  259,  268,  257,  273,  282,  264,  283,
      284,  266,  286,  287,  262,  281,  279,  277,  280,  288,
      289,  278,  282,  290,  284,  292,  291,  294,  295,  296,
      297,  298,  287,  286,  299,  301,  300,  304,  283,  302,
      292,  288,  291,  297,  298,  295,  290,  305,  301,  289,

      306,  308,  309,  310,  294,  304,  302,  313,  296,  300,
      314,  299,  315,  316,  318,  322,  317,  308,  305,  321,
      323,  309,  324,  326,  330,  332,  331,  327,  316,  306,
      313,  317,  342,  334,  343,  310,  326,  324,  327,  330,
      314,  331,  315,  318,  323,  345,  346,  321,  334,  322,
      347,  352,  353,  354,  332,  342,  355,  343,  345,  362,
      366,  346,  367,  358,  360,  368,  371,  369,  354,  355,
      370,  372,  379,  377,  352,  353,  373,  347,  358,  360,
      368,  369,  378,  376,  370,  375,  367,  374,  362,  366,
      371,  365,  373,  364,  363,  361,  359,  357,  356,  372,

      377,  382,  382,  382,  382,  383,  383,  383,  383,  385,
      385,  385,  385,  386,  386,  386,  386,  387,  351,  387,
      388,  350,  388,  388,  390,  349,  390,  390,  348,  344,
      341,  340,  339,  338,  337,  336,  335,  333,  329,  328,
      325,  320,  319,  312,  311,  307,  303,  293,  285,  276,
      275,  274,  272,  271,  269,  267,  263,  261,  247,  239,
      234,  233,  224,  218,  212,  208,  198,  189,  186,  182,
      179,  160,  158,  154,  153,  143,  121,  114,  104,   93,
       91,   86,   84,   82,   80,   78,   72,   70,   68,   65,
       63,   62,   33,   32,   21,   14,   12,   11,   10,    9,

        5,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[140] =
    {   0,
0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define YY_NO_INPUT 1
#line 8 "scanner.l"

#include <stdio.h>
#include "parser.h"
#include "list.h"

void erro_lexico();

extern Str_table *st;
extern char text_ant[100];
extern int text_ant_tam;

#line 781 "scanner.c"

#line 783 "scanner.c"

#define INITIAL 0
#define comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 34 "scanner.l"


#line 37 "scanner.l"
	/* Ignorados */

#line 1005 "scanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 382 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 702 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 39 "scanner.l"
{ BEGIN(comment); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "scanner.l"
{ /* Fazer nada */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "scanner.l"
{ /* Fazer nada */ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 42 "scanner.l"
{ /* Fazer nada */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "scanner.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 45 "scanner.l"
{ /* Fazer nada */ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "scanner.l"
{ /* Fazer nada */ }
	YY_BREAK
/* Palavras reservadas */
case 8:
YY_RULE_SETUP
#line 51 "scanner.l"
{ return BREAK; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 52 "scanner.l"
{ return CASE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 "scanner.l"
{ return CATCH; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 54 "scanner.l"
{ return CLASS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 "scanner.l"
{ return CONST_RW; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "scanner.l"
{ return CONTINUE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 57 "scanner.l"
{ return DEBUGGER; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 58 "scanner.l"
{ return DEFAULT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 59 "scanner.l"
{ return DELETE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 60 "scanner.l"
{ return DO; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "scanner.l"
{ return ELSE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 "scanner.l"
{ return ENUM; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 63 "scanner.l"
{ return EXPORT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 64 "scanner.l"
{ return EXTENDS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 65 "scanner.l"
{ return FALSE_RW; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 66 "scanner.l"
{ return FINALLY; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 67 "scanner.l"
{ return FOR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 68 "scanner.l"
{ return FUNCTION; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 69 "scanner.l"
{ return IF; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 "scanner.l"
{ return IMPLEMENTS; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "scanner.l"
{ return IMPORT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 "scanner.l"
{ return IN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 "scanner.l"
{ return INSTANCEOF; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 "scanner.l"
{ return INTERFACE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 75 "scanner.l"
{ return LET; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 76 "scanner.l"
{ return NEW; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 "scanner.l"
{ return NULL_RW; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "scanner.l"
{ return PACKAGE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "scanner.l"
{ return PRIVATE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "scanner.l"
{ return PROTECTED; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 81 "scanner.l"
{ return PUBLIC; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 82 "scanner.l"
{ return RETURN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 83 "scanner.l"
{ return SUPER; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 84 "scanner.l"
{ return SWITCH; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 85 "scanner.l"
{ return THIS; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 86 "scanner.l"
{ return THROW; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 87 "scanner.l"
{ return TRUE_RW; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 88 "scanner.l"
{ return TRY; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 89 "scanner.l"
{ return TYPEOF; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "scanner.l"
{ return VAR; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 91 "scanner.l"
{ return VOID_RW; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "scanner.l"
{ return WHILE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 93 "scanner.l"
{ return WITH; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 94 "scanner.l"
{ return AWAIT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 95 "scanner.l"
{ return YIELD; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 96 "scanner.l"
{ return STATIC; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 97 "scanner.l"
{ return AS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 98 "scanner.l"
{ return ASYNC; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 99 "scanner.l"
{ return FROM; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 100 "scanner.l"
{ return GET; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 101 "scanner.l"
{ return OF; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 102 "scanner.l"
{ return SET; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 103 "scanner.l"
{ return TARGET; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "scanner.l"
{ return ANY; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "scanner.l"
{ return BOOLTYPE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "scanner.l"
{ return CONSTRUCTOR; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "scanner.l"
{ return DECLARE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "scanner.l"
{ return MODULE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 "scanner.l"
{ return REQUIRE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "scanner.l"
{ return NEVER; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 "scanner.l"
{ return NUMBER; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 "scanner.l"
{ return STRING; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 "scanner.l"
{ return SYMBOL; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 114 "scanner.l"
{ return TYPE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 115 "scanner.l"
{ return UNDEFINED; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 116 "scanner.l"
{ return UNKNOWN; }
	YY_BREAK
/* Pontuadores */
case 74:
YY_RULE_SETUP
#line 121 "scanner.l"
{ return ASSIGN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 122 "scanner.l"
{ return ARROW; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 123 "scanner.l"
{ return COMMA; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 124 "scanner.l"
{ return SEMI; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 125 "scanner.l"
{ return COLON; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 126 "scanner.l"
{ return TERNARY; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 127 "scanner.l"
{ return CHAIN; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 128 "scanner.l"
{ return PIPELINE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 129 "scanner.l"
{ return DOT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 130 "scanner.l"
{ return SPREAD; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 132 "scanner.l"
{ return PLUS; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 133 "scanner.l"
{ return INCREMENT; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 134 "scanner.l"
{ return PLUS_ASSIGN; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 135 "scanner.l"
{ return SUB; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 136 "scanner.l"
{ return DECREMENT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 137 "scanner.l"
{ return SUB_ASSIGN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 138 "scanner.l"
{ return MULT; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 139 "scanner.l"
{ return MULT_ASSIGN; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 140 "scanner.l"
{ return DIV; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 141 "scanner.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 142 "scanner.l"
{ return EXP; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 143 "scanner.l"
{ return EXP_ASSIGN; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 144 "scanner.l"
{ return REM; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 145 "scanner.l"
{ return REM_ASSIGN; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 147 "scanner.l"
{ return BITWISE_NOT; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 148 "scanner.l"
{ return BITWISE_AND; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 149 "scanner.l"
{ return BITWISE_AND_ASSIGN; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 150 "scanner.l"
{ return BITWISE_OR; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 151 "scanner.l"
{ return BITWISE_OR_ASSIGN; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 152 "scanner.l"
{ return BITWISE_XOR; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 153 "scanner.l"
{ return BITWISE_XOR_ASSIGN; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 155 "scanner.l"
{ return LOGICAL_NOT; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 156 "scanner.l"
{ return LOGICAL_NULL; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 157 "scanner.l"
{ return LOGICAL_NULL_ASSIGN; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 158 "scanner.l"
{ return LOGICAL_AND; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 159 "scanner.l"
{ return LOGICAL_AND_ASSIGN; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 160 "scanner.l"
{ return LOGICAL_OR; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 161 "scanner.l"
{ return LOGICAL_OR_ASSIGN; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 163 "scanner.l"
{ return EQ; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 164 "scanner.l"
{ return EQ_STRICT; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 165 "scanner.l"
{ return INEQ; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 166 "scanner.l"
{ return INEQ_STRICT; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 167 "scanner.l"
{ return LT; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 168 "scanner.l"
{ return LT_EQ; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 169 "scanner.l"
{ return GT; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 170 "scanner.l"
{ return GT_EQ; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 172 "scanner.l"
{ return LSHIFT; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 173 "scanner.l"
{ return LSHIFT_ASSIGN; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 174 "scanner.l"
{ return RSHIFT; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 175 "scanner.l"
{ return RSHIFT_ASSIGN; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 176 "scanner.l"
{ return RSHIFT_UNSIGNED; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 177 "scanner.l"
{ return RSHIFT_UNSIGNED_ASSIGN; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 179 "scanner.l"
{ return LPAR; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 180 "scanner.l"
{ return RPAR; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 181 "scanner.l"
{ return LBRACE; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 182 "scanner.l"
{ return RBRACE; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 183 "scanner.l"
{ return LBRACKET; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 184 "scanner.l"
{ return RBRACKET; }
	YY_BREAK
/* Valores */
case 132:
YY_RULE_SETUP
#line 189 "scanner.l"
{ return INT_VAL; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 190 "scanner.l"
{ return REAL_VAL; }
	YY_BREAK
case 134:
/* rule 134 can match eol */
YY_RULE_SETUP
#line 191 "scanner.l"
{addStr(&st, yylineno, yytext); return STR_VAL; }
	YY_BREAK
case 135:
/* rule 135 can match eol */
YY_RULE_SETUP
#line 192 "scanner.l"
{addStr(&st, yylineno, yytext); return STR_VAL; }
	YY_BREAK
case 136:
/* rule 136 can match eol */
YY_RULE_SETUP
#line 193 "scanner.l"
{addStr(&st, yylineno, yytext); return STR_VAL; }
	YY_BREAK
/* Identificadores */
case 137:
YY_RULE_SETUP
#line 198 "scanner.l"
{ strcpy(text_ant,yytext); return ID; }
	YY_BREAK
/* Erros */
case 138:
YY_RULE_SETUP
#line 203 "scanner.l"
{ erro_lexico(); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 205 "scanner.l"
ECHO;
	YY_BREAK
#line 1777 "scanner.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 382 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 382 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 381);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 205 "scanner.l"


void erro_lexico()
{
	// Leitura de simbolo desconhecido
	fprintf(yyout, "LEXICAL ERROR (%d): Unknown symbol %s\n", yylineno, yytext);
	exit(EXIT_FAILURE);
}
